### ISSUE TITLE
(단순궁금) SuperModel 라이브러리는 무엇인가요?

### ISSUE THREAD

**Issue by minhoryang** [StyleShare/swift-style-guide#1]
좋은 글 잘 보고있습니다. 감사합니다.
이리저리 찾아보아도 Python용 라이브러리만 보이고, iOS나 ObjC/Swift용으로는 보이지 않아 질문합니다.

**Comment by devxoul** [comment]
Swift 모델 프레임워크입니다.
https://github.com/SwiftyModel/SwiftyModel 로 변경됐습니다.

**Comment by minhoryang** [comment]
감사합니다:)
