### ISSUE TITLE
클래스와 구조체 관련 질문

### ISSUE THREAD

**Issue by AppleCEO** [StyleShare/swift-style-guide#5]
클래스와 구조체 내부에서는 self를 명시적으로 사용합니다.

라고 쓰여있는데요.

그렇다면 내부에 있는 프로퍼티를 사용할 때 self 를 붙여야한다는 말씀이신가요?

예를 들어 ViewController 에서 내부 view 에 접근할 때 view.addSubview(view:) 보다는 self.view.addSubview(view:) 로 호출하는 것이 좋다는 말씀이시죠?

감사합니다.

**Comment by kikillers** [comment]
글로벌 스코프랑 구분하기 위해 항상 self 사용하신데요

**Comment by AppleCEO** [comment]
아.. 글로벌 객체인지 내부에 있는 객체인기 구분하기 위해서 인가보군요. 감사합니다.
